cleaner dockerfile, php8.0, composer.lock, fixes

diff --git a/vimbadmin-ubuntu/Dockerfile b/vimbadmin-ubuntu/Dockerfile
--- a/vimbadmin-ubuntu/Dockerfile
+++ b/vimbadmin-ubuntu/Dockerfile
@@ -1,4 +1,4 @@
-FROM	eilandert/apache-phpfpm:7.4
+FROM	eilandert/apache-phpfpm:8.0
 LABEL	maintainer="Thijs Eilander <eilander@myguard.nl>"
 ENV     DEBIAN_FRONTEND="noninteractive"
 
@@ -6,30 +6,33 @@ ENV	INSTALL_PATH=/opt/vimbadmin
 
 COPY	bootstrap.sh /bootstrap.sh
 
-RUN apt-get update && apt-get -y install --no-install-recommends git unzip \
-  && git clone \
-     --recurse-submodules \
-     --depth=1 \
-     -c advice.detachedHead=false \
-     -j`nproc` \
-     https://github.com/opensolutions/ViMbAdmin.git \
-     ${INSTALL_PATH} \
-  && cd ${INSTALL_PATH} \
-  && rm -rf /etc/php && cp -r /etc/php.orig /etc/php \
-  && composer update --prefer-dist --no-dev \
-  && composer config -g secure-http false \
-  && composer install --prefer-dist --no-dev \
-  && rm -rf /etc/php && mkdir -p /etc/php \
-  && chown -R www-data:www-data ${INSTALL_PATH}/var \
-  && cp -r ${INSTALL_PATH}/application/configs ${INSTALL_PATH}/application/configs.orig \	
-  && echo "Include ${INSTALL_PATH}/application/configs/httpd.conf" > /etc/apache2.orig/sites-enabled/000-default.conf \
-  && echo "php_admin_flag[opcache.enable] = 1" >> /etc/php.orig/${PHPVERSION}/fpm/pool.d/www.conf \
-  && rm ${INSTALL_PATH}/application/configs.orig/application.ini.vagrant \
-  && apt-get -y purge git unzip mailutils nullmailer \
-  && apt-get -y autoremove && apt-get -y clean && apt-get -y autoclean \
-  && rm -rf /var/lib/apt/lists/*  \
-  && rm -rf ${INSTALL_PATH}/.git /root/.composer /root/.cache /root/.local \
-  && chmod +x /bootstrap.sh 
+RUN set -ex ;\
+    apt-get update && apt-get -y install --no-install-recommends curl git unzip ;\
+    mkdir -p ${INSTALL_PATH} ;\
+    curl -fSL https://github.com/opensolutions/ViMbAdmin/archive/master.tar.gz | \
+      tar xz --strip-components=1 -C ${INSTALL_PATH} ;\
+    cd ${INSTALL_PATH} ;\
+    rm -rf /etc/php && cp -r /etc/php.orig /etc/php ;\
+    rm composer.lock ;\
+    composer config -g secure-http false ;\
+    composer require doctrine/orm -W --prefer-dist ;\
+    composer update --prefer-dist --no-dev ;\
+    chown -R www-data:www-data ${INSTALL_PATH}/var ;\
+    cp -r ${INSTALL_PATH}/application/configs ${INSTALL_PATH}/application/configs.orig ;\
+    echo "Include ${INSTALL_PATH}/application/configs/httpd.conf" > /etc/apache2.orig/sites-enabled/000-default.conf ;\
+    echo "php_admin_flag[opcache.enable] = 1" >> /etc/php.orig/${PHPVERSION}/fpm/pool.d/www.conf ;\
+    echo "php_admin_value[opcache.jit_buffer_size]=64M" >> /etc/php.orig/${PHPVERSION}/fpm/pool.d/www.conf ;\
+    echo "php_admin_value[memory_limit]=64M" >> /etc/php.orig/${PHPVERSION}/fpm/pool.d/www.conf ;\
+    echo "php_admin_flag[display_errors]=Off" >> /etc/php.orig/${PHPVERSION}/fpm/pool.d/www.conf ;\
+    composer clear-cache ;\
+    rm -rf /etc/php && mkdir -p /etc/php ;\
+    rm ${INSTALL_PATH}/application/configs.orig/application.ini.vagrant ;\
+    apt-get -y purge curl git unzip mailutils nullmailer ;\
+    apt-get -y autoremove && apt-get -y clean && apt-get -y autoclean ;\
+    rm -rf /var/lib/apt/lists/*  ;\
+    rm -rf ${INSTALL_PATH}/.git /root/.composer /root/.cache /root/.local ;\
+    sed -i 's/defaults.mailbox.password_scheme\ \= \"dovecot:BLF-CRYPT\"/defaults.mailbox.password_scheme\ \= \"crypt:sha512"/' ${INSTALL_PATH}/application/configs.orig/application.ini.dist ;\
+    chmod +x /bootstrap.sh
 
 COPY httpd.conf ${INSTALL_PATH}/application/configs.orig/
 
